name: fronted_abj
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  audioplayers:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/musica.mp3
    - assets/Imagenes/imagenes_bienvenida/logo.png
    - assets/Imagenes/imagenes_edad/
    - assets/Imagenes/imagenes_nombre/
    - assets/Imagenes/imagenes_curso_matematicas/
    - assets/Imagenes/imagenes_curso_ciencia/
    - assets/Imagenes/imagenes_curso_comunicacion/
    - assets/Imagenes/imagenes_seleccionar_cursos/
    - assets/Imagenes/Juegos/JuegosMate/Juego2/graphics/
    - assets/Imagenes/Juegos/JuegosMate/Juego2/graphics/AÎ”B.png
    - assets/Imagenes/Juegos/files/palabrasJuegoOrtografia.csv
    - assets/Imagenes/Juegos/JuegosComu/Juego1/
    - assets/Imagenes/Juegos/files/partesDelCuerpoCien.csv
    - assets/Imagenes/Juegos/JuegosCien/Juego1/
    - assets/Imagenes/imagenes_perfil/
    - assets/Imagenes/Juegos/files/animalesTiposCien.csv
    - assets/Imagenes/Juegos/JuegosCien/Juego2/
